name: publish
run-name: ${{ github.actor }} is publishing
on:
  push:
    branches:
      - main

jobs:
  many-linux-x86-64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Publish wheel
        uses: PyO3/maturin-action@v1
        env: 
          MATURIN_USERNAME: __token__
          MATURIN_PASSWORD: ${{ secrets.PYPI_PUBLISH_TOKEN }}
        with:
          command: publish
  windows-x86-64:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Publish wheel
        uses: PyO3/maturin-action@v1
        env: 
          MATURIN_USERNAME: __token__
          MATURIN_PASSWORD: ${{ secrets.PYPI_PUBLISH_TOKEN }}
        with:
          command: publish
          args: --no-sdist